### ISSUE TITLE
PHP 7.0 compatibility issue

### ISSUE THREAD

**Issue by sorenweber** [Klap-in/dokuwiki-plugin-templatepagename#8]
Hi,

I get the following in my apache error log (using Ubuntu Server 16.04 with PHP 7.0):
`PHP Warning:  Declaration of action_plugin_templatepagename_TemplatePageName::register(Doku_Event_Handler &$controller) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller) in /var/www/html/dokuwiki/lib/plugins/templatepagename/action/TemplatePageName.php on line 0, referer: https://dokuwiki/dokuwiki/doku.php/start?do=media&ns=
`

**Comment by FatherMcGruder** [comment]
Did you ever find a resolution?

**Comment by Klap-in** [comment]
It should be fixed by /8e72b7a09344db4d6253e969993a1e42f46cdf42

Either, the update date was not up-to-date so the extension manager didn't find the last update.
If you update the plugin, then you receive the last version with this fix.
